<a href="https://colab.research.google.com/github/Stonetenth2005/Machine-Learning/blob/main/22-Feature-Transformation/feature_construction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/train (2).csv')[['Age', 'Pclass', 'SibSp', 'Parch', 'Survived']]

In [ ]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [ ]:
df.dropna(inplace=True)

In [ ]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=10))

np.float64(0.6921165884194054)

# Applying Feature Construction

In [ ]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

  Making a family type column, 0 -> alone, 1 -> small, 2 -> big

In [ ]:
def famType(num):
  if(num == 1):
    return 0
  elif(num > 1 and num <= 4):
    return 1
  else:
    return 2

In [ ]:
X['Family_type'] = X['Family_size'].apply(famType)
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [ ]:
X.drop(columns=['SibSp', 'Parch', 'Family_size'], inplace=True)
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [ ]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=10))

np.float64(0.6963810641627542)

Notice the increase in crossval score